"use strict";
exports.__esModule = true;
exports.detail = void 0;
var detail;
(function (detail) {
    detail["name"] = "Please enter your name. :  ";
    detail["age"] = "Please enter your age. :  ";
    detail["contactNo"] = "Please enter your contact number.:  ";
    detail["email"] = "Please enter your email.:  ";
    detail["dateOfBirth"] = "Please enter your date of birth (DD-MM-YEAR):  ";
    detail["accountNo"] = "Auto Generated : ";
    detail["username"] = "Please create your user Id.:  ";
    detail["password"] = "Please create a password :  ";
    detail["deposit"] = "Please enter the amount of the deposit:  ";
    detail["withdraw"] = "Please enter the amount to withdraw.:  ";
    detail["loanAmount"] = "Please enter the amount.:  ";
    detail["userInput"] = "Please enter your user Id.:  ";
    detail["userPass"] = "Please enter your password.:  ";
    detail["moneyTransfer"] = "Please enter amount to transfer:  ";
    detail["receiverAccountNo"] = "Please enter the account number of the receiver:  ";
    detail["savingAccount"] = "Saving";
    detail["currentAccount"] = "Current";
    detail["userDB"] = "./DB/user.json";
    detail["bankDB"] = "../DB/user.json";
    detail["adminDB"] = "./DB/admin.json";
    detail["adminDb"] = "../DB/admin.json";
    detail["fs"] = "fs";
    detail["path"] = "path";
    detail["prompt"] = "prompt-sync";
    detail["amountHolder"] = "Please choose  one option \n    1. Rs.0 amount Holder\n    2. Rs. < 1 Lakh amount Holder\n    3. Rs. > 1 Lakh amount Holder\n    4. Exit\n    ";
    detail["loanSection"] = "Please choose  one option \n    1. Apply for Loan (Upto 5 Lakh)\n    2. Loan Status \n    3. Paid Loan\n    4. Loan Amount\n    5. Exit   \n    ";
    detail["bankLogin"] = "Please choose  one option \n    1. User Login\n    2. Admin Login\n    ";
    detail["userLogin"] = "Please choose one  option :\n    \n     1. Create a New Account\n     2. Show Details \n     3. Deposit (Upto 7 Digit Amount)\n     4. Withdraw\n     5. View Balance\n     6. Loan Section \n     7. Money Transfer \n     8. Exit\n     ";
    detail["adminLogin"] = "Please choose option :\n     1. User Details \n     2. Account Holder details Based On amount\n     3. Saving Accounts  (Amount less than 1 Lakh)\n     4. Current Accounts (Amount more than 1 Lakh)\n     5. Approve Loan \n     6. Loan Holder\n     7. Bank Statement \n     8. Exit\n     ";
})(detail = exports.detail || (exports.detail = {}));
